import { IVocabs } from "../../medium";
/* tslint:disable */
export const UsVocabs: IVocabs = {
    //
    login: "Login",
    logout: "Logout",
    register: "Register",
    ok: "Ok",
    cancel: "Cancel",
    retry: "Retry",
    yes: "Yes",
    no: "No",
    save: "Save",
    add: "Ass",
    submit: "Submit",
    edit: "Edit",
    update: "Update",
    select: "Select",
    home: "Home",
    about: "About Us",
    contact_us: "Contact Us",
    send_reset: "Send reset password",
    forget_pass: "Forget password",
    operations: "Operations",
    description: "Dexription",
    year: "Year",
    month: "Month",
    hour: "Hour",
    minute: "Minute",
    filemanager: "File Manager",
    app_update: "Updating...",
    no_records: "No record found",
    profile: "Profile",
    // general fields
    fld_id: "Id",
    fld_status: "Status",
    fld_desc: "Description",
    fld_type: "Type",
    fld_date: "Date",
    fld_title: "Title",
    // role model
    mdl_role: "Roles",
    role: "Role",
    fld_permission: "Permission",
    fld_resource: "Resource",
    fld_action: "Action",
    // log model
    mdl_log: "Logs",
    fld_level: "Level",
    fld_message: "Message",
    fld_method: "Method",
    fld_file: "File",
    // support model
    mdl_support: "Support",
    // context
    mdl_context: "Predefined Texts",
    fld_key: "Key",
    // user model
    mdl_user: "Users",
    fld_username: "Username",
    fld_password: "Password",
    fld_conf_password: "Confirm Password",
    fld_name: "Name",
    fld_firstname: "First Name",
    fld_lastname: "Last Name",
    fld_user: "User",
    fld_email: "Email",
    fld_mobile: "Mobile",
    fld_gender: "Gender",
    fld_image: "Image",
    fld_phone: "Phone",
    fld_address: "Address",
    fld_sourceapp: "Source App",
    //
    enum_user: "User",
    enum_admin: "Admin",
    enum_active: "Active",
    enum_inactive: "Inactive",
    enum_male: "Male",
    enum_female: "Female",
    enum_error: "Error",
    enum_warn: "Warning",
    enum_info: "Info",
    enum_enduser: "End User",
    enum_panel: "Admin Panel",
    //
    title_record_detail: "Showing % records of %",
    title_record_add: "Adding new %",
    title_record_edit: "Editing %",
    //
    err_wrong_user_pass: "Username/Password combination does not match",
    err_required: "This field is required",
    err_min_value: "Minimum value of this record is %",
    err_max_value: "Maximum value of this record is %",
    err_min_length: "Minimum length of this record is %",
    err_max_length: "Maximum length of this record is %",
    err_ext_length: "This field value must be of length %",
    err_duplicate: "This value has already been taken",
    err_file_type: "File type is not valid",
    err_file_size: "Maximum allowed file size is %",
    err_enum: "Selected value is not valid",
    err_phone: "Invalid phone number",
    err_url: "Invalid address",
    err_validation: "Invalid data",
    err_email: "Invalid email address",
    err_invalid_phone: "Phone number does not exist. Please register",
    err_db_conn: "Error connecting to database",
    err_db_op: "Database operation failure",
    err_dup_entry: "Duplicate entry",
    err_db_query: "Database query error",
    err_db_insert: "Database insertion error",
    err_db_update: "Database update error",
    err_db_delete: "Database deletion error",
    err_db_driver: "Invalid database driver",
    err_db_record_cnt: "Record not found",
    err_db_no_record: "Record not found",
    err_unauthorized: "Unauthorized",
    err_forbidden: "Forbidden",
    err_bad_req: "Bad Request",
    err_server: "Server Error",
    err_token: "Invalid token",
    err_input: "Input is not valid",
    err_op: "Invalid operation",
    err_file: "File system error",
    err_device: "Client device error",
    err_net_conn: "Error on network connection",
    err_unknown: "Unknown error",
    err_admin_login: "Admin is not allowed to login into application",
    err_user_admin_login: "Only admin my enter the control panel",
    err_none_user_login: "You have to register in order to login to application",
    err_sms: "Some thing goes wrong on sending text message. Please try again later",
    "unexpected end of json input": "Error connecting to server",
    "unexpected end of input": "Error connecting to server",
    //
    info_add_record: "Record #% has been added successfully",
    info_update_record: "Record #% has been updated successfully",
    info_delete_record: "Record #% has been deleted successfully",
    info_forget: "New password has been sent to your number",
    //
    msg_delete_confirm: "Are you sure about deleting %?",
    msg_inprogress: "Operation in progress",
    msg_register_ok: "Congratulations! You have been registered successfully",
    msg_wait: "Please wait!",
    txt_change_pass: "Change password",
    txt_change_image: "Change image",
    register_accept: "I agree with rules and laws",
    call_support: "Call support",
    //////////////////////////////
    // application
};
