import {IVocabs} from "../../core/Dictionary";

export const IrVocabs: IVocabs = {
    //
    login: 'ورود',
    logout: 'خروج',
    register: 'ثبت نام',
    yes: 'بلی',
    no: 'خیر',
    save: 'ذخیره',
    add: 'افزودن',
    submit: 'ارسال',
    edit: 'ویرایش',
    update: 'بروزرسانی',
    cancel: 'لغو',
    dashboard: 'خانه',
    about: 'درباره ما',
    contact_us: 'تماس با ما',
    send_reset: 'ارسال کد بازنشانی',
    forget_pass: 'فراموشی کلمه عبور',
    operations: 'عملیات',
    description: 'توضیحات',
    year: 'سال',
    month: 'ماه',
    hour: 'ساعت',
    minute: 'دقیقه',
    // model fields
    fld_id: 'کد',
    fld_username: 'نام کاربری',
    fld_password: 'کلمه عبور',
    fld_conf_password: 'تکرار کلمه عبور',
    fld_name: 'نام',
    fld_user: 'کاربر',
    fld_email: 'ایمیل',
    fld_gender: 'جنسیت',
    fld_image: 'تصویر',
    fld_desc: 'توضیح',
    fld_status: 'وضعیت',
    fld_permission: 'اجازه',
    fld_resource: 'منبع',
    fld_action: 'عمل',
    fld_phone: 'شماره تماس',
    fld_address: 'آدرس',
    fld_date: 'تاریخ',
    //
    mdl_role: 'نقش',
    mdl_request: 'درخواست ها',
    //
    enum_active: 'فعال',
    enum_inactive: 'غیرفعال',
    enum_male: 'مرد',
    enum_female: 'زن',
    //
    title_record_detail: 'نمایش % شماره %',
    title_record_add: 'افزودن % جدید',
    title_record_edit: 'ویرایش %',
    //
    err_wrong_user_pass: 'نام کاربری یا کلمه عبور وارد شده صحیح نمی باشد',
    err_required: 'مقداردهی این فیلد الزامی می باشد',
    err_min_value: 'حداقل مقدار ورودی % می باشد',
    err_max_value: 'حداکثر مقدار ورودی % می باشد',
    err_min_length: 'حداقل تعداد کاراکتر  % می باشد',
    err_max_length: 'حداکثر تعداد کاراکتر % می باشد',
    err_duplicate: 'مقدار وارد شده تکراری می باشد',
    err_file_type: 'نوع فایل صحیح نمی باشد',
    err_file_size: 'حجم فایل باید کمتر از % باشد',
    err_enum: 'گزینه وارد شده معتبر نمی باشد',
    err_phone: 'شماره تلفن وارد شده معتبر نمی باشد',
    err_validation: 'داده های ارسال شده معتبر نمی باشد',
    err_invalid_phone: 'شماره شما یافت نشد. لطفا ثبت نام نمایید',
    //
    info_add_record: 'رکورد شماره % با موفقیت درج گردید',
    info_update_record: 'رکورد شماره % با موفقیت بروزرسانی گردید',
    info_delete_record: 'رکورد شماره % با موفقیت حذف گردید',
    info_forget: 'کلمه عبور جدید به شماره شما ارسال گردید',
    //
    msg_delete_confirm: 'آیا در مورد حذف % مطمین هستید?',
    msg_inprogress: 'عملیات در حال اجرا...',
    msg_wait: 'لطفا منتظر باشید!',
    txt_change_pass: 'تغییر کلمه عبور',
    //////////////////////////////
    // application
    shop: 'فروشگاه',
    repair_shop: 'تعمیرگاه ها',
    repair_call: 'تعمیر در محل',
    health_tec: 'کارشناس سلامت خودرو',
    car_sos: 'امداد خودرو',
    vip: 'وی آی پی',
    fld_title: 'عنوان',
    fld_content: 'محتوی',
    // mechanic shop
    mdl_mechanicshop: 'لیست تعمیرگاه ها',
    fld_square: 'مساحت',
    fld_lng: 'طول جغرافیایی',
    fld_lat: 'عرض جغرافیایی',
    fld_type: 'نوع',
    fld_isrental: 'ملک اجاره ای ؟',
    fld_licenseno: 'شماره جواز',
    fld_education: 'تحصیلات',
    fld_capacity: 'ظرفیت',
    fld_nopersonnel: 'تعداد کارکنان',
    fld_rank: 'رتبه',
    fld_background: 'پس زمینه',
    enum_verified: 'مجاز',
    fld_region: 'ناحیه',
    fld_rate: 'امتیاز',
    txt_manager: 'مدیریت %',
    // regions
    mdl_region: 'ناحیه',
    mechanicshops: 'تعمیرگاه ها',
    regions: 'نواحی',
    cities: 'شهرها',
    states: 'استان ها',
    mdl_state: 'استان',
    fld_state: 'استان',
    mdl_city: 'شهر',
    fld_city: 'شهر',
    roles: 'نقش ها',
    map: 'نقشه',
    list: 'لیست',
    // users
    users: 'کاربران',
    mdl_user: 'کاربر',
    fld_mobile: 'موبایل',
    fld_birthDate: 'تاریخ تولد',
    enum_staff: 'کارکنان',
    enum_mechanic: 'مکانیک',
    enum_technician: 'کارشناس',
    enum_user: 'کاربر',
    fld_role: 'نقش',
    fld_link: 'لینک',
    // advs
    adv: 'تبلیغات',
    mdl_adv: 'تبلیغات',
    // brands
    brand: 'برند',
    brands: 'برندها',
    // comments
    comments: 'نظرات',
    comment: 'نظر',
    mdl_comment: 'نظرات',
    section: 'بخش',
    // request
    request: 'درخواست',
    send_request: 'ارسال درخواست',
    request_for_date: 'درخواست برای تاریخ',
    add_car: 'افزودن خودرو',
    car: 'خودرو',
    mdl_health: 'سلامت',
};